PAAS-1377: wait for jcustomer to be up after restart & redeploy

diff --git a/jcustomer/jcustomer_actions.yml b/jcustomer/jcustomer_actions.yml
--- a/jcustomer/jcustomer_actions.yml
+++ b/jcustomer/jcustomer_actions.yml
@@ -69,28 +69,29 @@ actions:
         if (resp.result != 0) return resp;
         return {"result": 0}
     - forEach(nodes.cp):
-        cmd[${@i.id}]: |-
-          sed -i "/<interface>/d" $HAZELCAST_CONFIG
-          sed -i "/<member>node/d" $HAZELCAST_CONFIG
-          envfile=$(find /opt/jcustomer/jcustomer/bin -name setenv)
-          if (grep -q UNOMI_HAZELCAST_TCPIP_MEMBERS $envfile); then
-            sed 's/\(.*HAZELCAST_TCPIP_MEMBERS=\).*/\1${globals.unomi_IPs}/' -i $envfile
-          else
-            echo "export UNOMI_HAZELCAST_TCPIP_MEMBERS=${globals.unomi_IPs}" >> $envfile
-          fi
-          sed -e '/UNOMI_CLUSTER_PUBLIC_ADDRESS/d' \
-              -e '/UNOMI_CLUSTER_INTERNAL_ADDRESS/d' \
-              -e '/UNOMI_ROOT_PASSWORD/d' \
-              -i $envfile
-          echo "export UNOMI_CLUSTER_PUBLIC_ADDRESS=${@i.url}" >> $envfile
-          echo "export UNOMI_CLUSTER_INTERNAL_ADDRESS=${@i.url}:9443" >> $envfile
-          echo "export UNOMI_ROOT_PASSWORD=${globals.unomi_root_password}" >> $envfile
-          systemctl is-active --quiet karaf && systemctl restart karaf || exit 0
-        user: root
-    - if ("${response.errOut}" != ""):
-        - return:
-            type: error
-            message: "An error occurred during hazelcast setup."
+        - cmd[${@i.id}]: |-
+            sed -i "/<interface>/d" $HAZELCAST_CONFIG
+            sed -i "/<member>node/d" $HAZELCAST_CONFIG
+            envfile=$(find /opt/jcustomer/jcustomer/bin -name setenv)
+            if (grep -q UNOMI_HAZELCAST_TCPIP_MEMBERS $envfile); then
+              sed 's/\(.*HAZELCAST_TCPIP_MEMBERS=\).*/\1${globals.unomi_IPs}/' -i $envfile
+            else
+              echo "export UNOMI_HAZELCAST_TCPIP_MEMBERS=${globals.unomi_IPs}" >> $envfile
+            fi
+            sed -e '/UNOMI_CLUSTER_PUBLIC_ADDRESS/d' \
+                -e '/UNOMI_CLUSTER_INTERNAL_ADDRESS/d' \
+                -e '/UNOMI_ROOT_PASSWORD/d' \
+                -i $envfile
+            echo "export UNOMI_CLUSTER_PUBLIC_ADDRESS=${@i.url}" >> $envfile
+            echo "export UNOMI_CLUSTER_INTERNAL_ADDRESS=${@i.url}:9443" >> $envfile
+            echo "export UNOMI_ROOT_PASSWORD=${globals.unomi_root_password}" >> $envfile
+          user: root
+        - if ("${response.errOut}" != ""):
+            return:
+              type: error
+              message: "An error occurred during hazelcast setup."
+        - api: environment.control.RestartNodeById
+          nodeId: ${@i.id}
 
   setupUnomi:
     - updateHazelcast
@@ -145,3 +146,20 @@ actions:
         }
       );
       return {"result": 0, "out": "Unlinked following environments: " + jahia_linked};
+
+  checkJcustomerHealthWhenStarting:
+    cmd [${this}]: |-
+        log_file="/var/log/jelastic-packages/checkJcustomerHealthWhenStarting"
+        setenv=$(find /opt/jcustomer/jcustomer/bin -name setenv)
+        karaf_pwd=$(grep UNOMI_ROOT_PASSWORD $setenv | cut -d"=" -f2 | sed 's,\s\+,,g')
+        timeout=120
+        echo "Jcustomer is starting...." >> $log_file
+        echo "Waiting for cxs/privacy/info to be ok" >> $log_file
+        while [ $timeout -gt 0 ]; do
+          curl -fsI /dev/null -u "karaf:$karaf_pwd" http://localhost:80/cxs/privacy/info && exit 0
+          sleep 1
+          let "timeout-=1"
+        done
+        echo "120 seconds timeout exeeded, exiting with error" >> $log_file
+        exit 1
+    user: root
