PAAS-1336: fix healthchecks

diff --git a/elasticsearch/elasticsearch_actions.yml b/elasticsearch/elasticsearch_actions.yml
--- a/elasticsearch/elasticsearch_actions.yml
+++ b/elasticsearch/elasticsearch_actions.yml
@@ -19,6 +19,5 @@ actions:
             exit 0
           fi
         fi
-        echo "[ERROR] There is an issue with the cluster, exiting" 1>&2
-        exit 1
+        echo "[ERROR] There is an issue with the cluster, exiting" 1>&2 && exit 1
       user: root
diff --git a/jcustomer/jcustomer_actions.yml b/jcustomer/jcustomer_actions.yml
--- a/jcustomer/jcustomer_actions.yml
+++ b/jcustomer/jcustomer_actions.yml
@@ -9,5 +9,5 @@ actions:
         karaf_credentials="karaf:$karaf_pwd"
         curl -fsI /dev/null -u "$karaf_credentials" http://localhost:80/cxs/privacy/info && exit 0
       fi
-      rc=$? && echo "[ERROR] jCustomer is unavailable, exiting" && exit $rc
+      echo "[ERROR] jCustomer is unavailable, exiting" 1>&2 && exit 1
     user: root
